
main_file: "two_ops1poly.pd"

midi_controllers:
 volume:
  midi_cc: 7
  value: 64
 program:
  midi_cc: 2
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16' ]
 resonance:
  midi_cc: 1
  value: 32
